// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAzqYN8RJNM1u00qHDrgizAg_YXe8B24',
    appId: '1:5122163078:android:97926b49827f08c203ec07',
    messagingSenderId: '5122163078',
    projectId: 'intercom-680a7',
    storageBucket: 'intercom-680a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAskdvKoypWOBilUylzLC13vqHBMihtcR8',
    appId: '1:5122163078:ios:4ba9cb53d45f5cc003ec07',
    messagingSenderId: '5122163078',
    projectId: 'intercom-680a7',
    storageBucket: 'intercom-680a7.appspot.com',
    androidClientId: '5122163078-71c1489oa290t2r9co0065qd1abttlua.apps.googleusercontent.com',
    iosClientId: '5122163078-7fj3k5tmvjdavqk6krfg7kpnmd98cn3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.appintercom',
  );
}
